sudo: false
language: python

python:
    - "3.4"
    - "3.5"
    - "3.6"

matrix:
  include:
    - python: "3.6"
      env: TOX_ENV=docs
      install: pip install tox
      script: tox -e $TOX_ENV
    - python: "3.6"
      env: TOX_ENV=flake8
      install: pip install tox
      script: tox -e $TOX_ENV
    # Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
    # https://github.com/travis-ci/travis-ci/issues/9815
    - python: 3.7
      dist: xenial
      sudo: true

install:
    - pip install tox-travis codecov

script:
    - tox

after_success: codecov

notifications:
    irc:
        channels:
            - "ircs://irc.megworld.co.uk:9000#exhibition"
        use_notice: true
